const DropdownActionTypes = {
	TOGGLE_PHOTO_DROPDOWN_HIDDEN: "TOGGLE_PHOTO_DROPDOWN_HIDDEN",
	EXTEND_PHOTO_DROPDOWN_HIDDEN: "EXTEND_PHOTO_DROPDOWN_HIDDEN",
	RETRACT_PHOTO_DROPDOWN_HIDDEN: "RETRACT_PHOTO_DROPDOWN_HIDDEN",
	TOGGLE_FILM_DROPDOWN_HIDDEN: "TOGGLE_FILM_DROPDOWN_HIDDEN"
};

export default DropdownActionTypes;
